### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by dinoseur** [kylewray/epic#1]
hello,
Can you show a example to explain how to run the code?

Thanks a lot.

**Comment by kylewray** [comment]
Hey,

Please forgive the delay in my response. You can run the code by:
1. Clone repo.
2. Run "make" in the "libepic" directory.
3. Run "catkin_make" in the root directory.
4. Run "roslaunch epic epic_nav_core_plugin_umass.launch"
5. Click a 2d nav goal in the gray space somewhere.

The "libepic" folder is just C++/CUDA/Python. You can try running "python3 libepic/tests/maps/maps.py visual" command; this lets you click on a OpenCV2 image to create the paths.

The "epic" root directory acts as a ROS package. So, you can actually just put it directly in a larger ROS project. The "nav_core" interface is standard to ROS. The better interface can be used with ROS service calls to the epic node. See the code for the handful of service calls; it should be pretty straight forward.

Kyle
